services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: itachique-api
  #   volumes:
  #     - .:/var/www
  #   depends_on:
  #     - db

  # nginx:
  #   image: nginx:1.25-alpine
  #   volumes:
  #     - ./.docker/nginx:/etc/nginx/conf.d
  #   ports:
  #     - 80:80

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: itachiqu_db
    ports:
      - "3304:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: itachiqu_db
    volumes:
      - ./.docker/db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: itachiqu_phpmyadmin
    ports:
      - 8004:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=host.docker.internal
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_PORT=3304
      - UPLOAD_LIMIT=512M
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    container_name: itachiqu_mailhog
    ports:
      - 1025:1025
      - 8005:8025

  redis:
    image: redis:latest
    container_name: itachiqu_redis
    ports:
      - 6379:6379
    networks:
      - network

volumes:
  volume:
    driver: local

networks:
  network:
    driver: bridge