#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint

# Bloquear o push se os testes falharem
if [ $? -ne 0 ]; then
  echo "Alguns arquivos estão mal formatados. Por favor, execute 'npm run lint' para corrigir os erros."
  exit 1
fi